// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");

function intEquals(message, a, b) {
  return Test.assertion(message, "Int equals", (function (a, b) {
                return a === b;
              }), a, b);
}

Test.test("Add", (function (param) {
        intEquals(undefined, 4, 2);
        return intEquals("1 + 2 === 3", 3, 3);
      }));

exports.intEquals = intEquals;
/*  Not a pure module */
