// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myArr = [
  4,
  8,
  7,
  14,
  55
];

function predicateFunction(element) {
  return element > 10;
}

var filteredArray = myArr.filter(predicateFunction);

console.log(filteredArray);

var anotherArray = [
  7,
  89,
  7,
  32,
  59
];

function isGreaterThanTen(element) {
  return element > 10;
}

var filteredArray2 = anotherArray.filter(isGreaterThanTen);

console.log(filteredArray);

exports.myArr = myArr;
exports.predicateFunction = predicateFunction;
exports.filteredArray = filteredArray;
exports.anotherArray = anotherArray;
exports.isGreaterThanTen = isGreaterThanTen;
exports.filteredArray2 = filteredArray2;
/* filteredArray Not a pure module */
