// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function timesTwo(input) {
  return (input << 1);
}

var anArray = [
  1,
  2,
  3,
  4,
  5
];

var arrayTimesTwo = anArray.map(timesTwo);

console.log(arrayTimesTwo);

exports.timesTwo = timesTwo;
exports.anArray = anArray;
exports.arrayTimesTwo = arrayTimesTwo;
/* arrayTimesTwo Not a pure module */
