// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

var arrInts = [
  1,
  2,
  3,
  4
];

console.log("arrInts:", arrInts);

console.log("arrInts[3]:", Caml_array.get(arrInts, 3));

Caml_array.set(arrInts, 1, 1);

console.log("arrInts[1]_Updated:", Caml_array.get(arrInts, 1));

var myArray = [
  "hello",
  "world",
  "how are you"
];

Caml_array.set(myArray, 0, "hey");

var pushedValue = myArray.push("bye");

console.log(pushedValue);

console.log(myArray);

var arrayTwo = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
];

var arrayTwo_reversed = Belt_Array.reverse(arrayTwo);

console.log("Size of arrayTwo:", arrayTwo.length);

console.log("arrayTwo Reversed: ", Belt_Array.reverse(arrayTwo));

exports.arrInts = arrInts;
exports.myArray = myArray;
exports.pushedValue = pushedValue;
exports.arrayTwo = arrayTwo;
exports.arrayTwo_reversed = arrayTwo_reversed;
/*  Not a pure module */
