// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./utils/Utils.bs.js");

var result = Utils.$$Math.divByTwo(3);

console.log(result);

exports.result = result;
/* result Not a pure module */
