// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var result = "they aren't the same";

console.log(result);

var x = 56;

var y = 78;

exports.x = x;
exports.y = y;
exports.result = result;
/*  Not a pure module */
