// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var array1 = [
  1,
  2,
  3
];

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

exports.array1 = array1;
exports.myList = myList;
/* No side effect */
