// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ballObject = {
  colour: "red",
  circumference: 30
};

var result = ballObject.circumference;

console.log(result);

exports.ballObject = ballObject;
exports.result = result;
/* result Not a pure module */
