// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var sentence = "This sentence ends with a number: ";

var fullStopString = (123).toString();

var concatenated = sentence + fullStopString;

console.log(concatenated);

var fullStop = 123;

exports.sentence = sentence;
exports.fullStop = fullStop;
exports.fullStopString = fullStopString;
exports.concatenated = concatenated;
/* fullStopString Not a pure module */
