// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function divByTwo(x) {
  return x / 2 | 0;
}

function divByTwoFloat(x) {
  return x / 2;
}

function add(a, b) {
  return a + b | 0;
}

function concat(a, b) {
  return a + b;
}

function addFloats(a, b) {
  return a + b;
}

var $$Math = {
  divByTwo: divByTwo,
  divByTwoFloat: divByTwoFloat,
  add: add,
  concat: concat,
  addFloats: addFloats
};

exports.$$Math = $$Math;
/* No side effect */
