// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

var arr = [
  "hello",
  "world",
  "how are you?"
];

var chris = [
  "Chris",
  "Tritton",
  "Coder"
];

var createArray = Caml_array.make;

console.log(Caml_array.make(42, "pssh"));

if (chris.length !== 3) {
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "Arrays.res",
          37,
          4
        ],
        Error: new Error()
      };
}

var tritton = chris[0];

var coder = chris[1];

var chris$1 = chris[2];

console.log(tritton + coder + chris$1);

exports.arr = arr;
exports.createArray = createArray;
exports.tritton = tritton;
exports.coder = coder;
exports.chris = chris$1;
/*  Not a pure module */
