// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("rescript/lib/js/caml_format.js");

var stringFromInt = Caml_format.caml_int_of_string("345");

console.log(stringFromInt);

var intFromString = String(1530);

console.log(intFromString);

exports.stringFromInt = stringFromInt;
exports.intFromString = intFromString;
/* stringFromInt Not a pure module */
