// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("-------------------as a tuple:--------------------");

var ourTuple = [
  "Han",
  "Solo",
  "Pilot",
  42
];

console.log(ourTuple);

function convertToRecord(param) {
  return {
          firstname: param[0],
          lastname: param[1],
          occupation: param[2],
          aNumber: param[3]
        };
}

console.log("------------------as a record:--------------------");

console.log(convertToRecord(ourTuple));

exports.ourTuple = ourTuple;
exports.convertToRecord = convertToRecord;
/*  Not a pure module */
