// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

function curriedFunction(param) {
  return 8 + param | 0;
}

var x = 10;

console.log(x);

exports.add = add;
exports.curriedFunction = curriedFunction;
exports.x = x;
/*  Not a pure module */
