// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function multiply(integerOneOpt, integerTwoOpt, param) {
  var integerOne = integerOneOpt !== undefined ? integerOneOpt : 11;
  var integerTwo = integerTwoOpt !== undefined ? integerTwoOpt : 22;
  return Math.imul(integerOne, integerTwo);
}

var x = multiply(undefined, undefined, undefined);

var y = multiply(10, undefined, undefined);

console.log(x);

console.log(y);

exports.multiply = multiply;
exports.x = x;
exports.y = y;
/* x Not a pure module */
