// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("rescript/lib/js/caml_format.js");

var $$function = Caml_format.caml_float_of_string;

var convert = Caml_format.caml_float_of_string;

console.log(Caml_format.caml_float_of_string("456.8977"));

exports.$$function = $$function;
exports.convert = convert;
/*  Not a pure module */
