// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var divide = Caml_int32.div;

console.log(9);

var divide2 = Caml_int32.div;

function x(param) {
  return param / 3 | 0;
}

function multiply(integerOne, integerTwo, param) {
  if (integerTwo !== undefined) {
    return Math.imul(integerOne, integerTwo);
  } else {
    return integerOne;
  }
}

var y = 5;

console.log(y);

exports.divide = divide;
exports.divide2 = divide2;
exports.x = x;
exports.multiply = multiply;
exports.y = y;
/*  Not a pure module */
