// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myList = {
  hd: 3,
  tl: {
    hd: 4,
    tl: {
      hd: 5,
      tl: {
        hd: 6,
        tl: /* [] */0
      }
    }
  }
};

var newMyList_1 = {
  hd: 2,
  tl: myList
};

var newMyList = {
  hd: 1,
  tl: newMyList_1
};

console.log(myList);

exports.myList = myList;
exports.newMyList = newMyList;
/*  Not a pure module */
