// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


for(var x = 0; x <= 8; ++x){
  console.log(x);
}

for(var i = 8; i >= 0; --i){
  console.log(i);
}

for(var i$1 = 0; i$1 <= 100; ++i$1){
  console.log("still not there yet...", i$1);
}

var $$break = {
  contents: false
};

while(!$$break.contents) {
  if (Math.random() > 0.3) {
    $$break.contents = true;
  } else {
    console.log("Still running");
  }
};

console.log("does this create a bad export?");

exports.$$break = $$break;
/*  Not a pure module */
