// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function multiply(integerOne, integerTwo, param) {
  if (integerTwo !== undefined) {
    return Math.imul(integerOne, integerTwo);
  } else {
    return integerOne;
  }
}

var y = 5;

console.log(y);

exports.multiply = multiply;
exports.y = y;
/*  Not a pure module */
