// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log(89);

console.log(4);

function getSecond(param, y) {
  return y;
}

console.log(987);

var y = 89;

var aTuple = [
  1,
  2,
  3
];

var x = 1;

var z = 3;

exports.y = y;
exports.aTuple = aTuple;
exports.x = x;
exports.z = z;
exports.getSecond = getSecond;
/*  Not a pure module */
