// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a) {
  return a + 5 | 0;
}

function multiply(a) {
  return Math.imul(a, 10);
}

function subtract(a) {
  return a - 1 | 0;
}

console.log("output of ans:", 89);

console.log("output of ans2:", 89);

console.log("output of ans3:", 89);

var ans = 89;

var ans2 = 89;

var ans3 = 89;

exports.add = add;
exports.multiply = multiply;
exports.subtract = subtract;
exports.ans = ans;
exports.ans2 = ans2;
exports.ans3 = ans3;
/*  Not a pure module */
