// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function swap(input1, input2) {
  return [
          input2,
          input1
        ];
}

console.log([
      "a string",
      45.126
    ]);

var title = "ReScript Sandbox Repo";

var mainTitle = title !== undefined ? "The name of this repo is: " + title : "We don't have the value";

console.log(mainTitle);

var titleIsMissing = false;

exports.swap = swap;
exports.titleIsMissing = titleIsMissing;
exports.title = title;
exports.mainTitle = mainTitle;
/*  Not a pure module */
