// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var parents = {
  father: "Anakin",
  mother: "Padme"
};

var luke = {
  firstname: "Luke",
  lastname: "Skywalker",
  occupation: "Jedi",
  parents: parents
};

console.log(luke);

exports.parents = parents;
exports.luke = luke;
/*  Not a pure module */
