// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getFirstname(person) {
  return person.firstname;
}

console.log("Luke");

var me = {
  age: 28,
  name: "Chris"
};

console.log(me);

var occupation = "Jedi";

console.log(occupation);

var lukeParents = {
  father: "Vader",
  mother: "Leya? I don't know"
};

var lukeNested = {
  firstname: "Luke",
  lastname: "Skywalker",
  occupation: "Jedi",
  parents: lukeParents
};

var mother = "Leya? I don't know";

var father = "Vader";

console.log("Leya? I don't knowVader");

function extractParents(param) {
  var match = param.parents;
  return match.father + match.mother;
}

console.log(extractParents(lukeNested));

var updatedLuke = {
  firstname: "Luke",
  lastname: "Skywalker",
  occupation: "farmer"
};

var luke = {
  firstname: "Luke",
  lastname: "Skywalker",
  occupation: "Jedi"
};

var firstname = "Luke";

exports.luke = luke;
exports.getFirstname = getFirstname;
exports.me = me;
exports.firstname = firstname;
exports.occupation = occupation;
exports.lukeParents = lukeParents;
exports.lukeNested = lukeNested;
exports.father = father;
exports.mother = mother;
exports.extractParents = extractParents;
exports.updatedLuke = updatedLuke;
/*  Not a pure module */
