// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var rescript = "yes";

var answer = rescript === "yes" ? "faster and safer and more difficult to learn" : "faster to learn, probably";

console.log(answer);

exports.rescript = rescript;
exports.answer = answer;
/* answer Not a pure module */
