// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ageAndName = [
  24,
  "Lil' ReScript",
  56
];

var my3dCoordinates = [
  20.0,
  30.5,
  100.0
];

exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
/* No side effect */
