// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("rescript/lib/js/string.js");

var value = "789 million billion zillion";

var valueOne = " is a string, and so it this";

console.log("789 million billion zillion is a string, and so it this");

var convert = $$String.uppercase_ascii;

console.log(convert);

var anotherConvert = $$String.uppercase_ascii;

exports.value = value;
exports.valueOne = valueOne;
exports.convert = convert;
exports.anotherConvert = anotherConvert;
/*  Not a pure module */
