// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function arityOfZero(param) {
  return 7;
}

console.log(arityOfZero);

console.log(7);

console.log(7);

console.log(7);

exports.arityOfZero = arityOfZero;
/*  Not a pure module */
