// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(field) {
  if (field) {
    if (field._0) {
      return "O";
    } else {
      return "X";
    }
  } else {
    return "";
  }
}

var someRandomField = /* Marked */{
  _0: /* Cross */0
};

console.log("output of someRandomField passed into toString: ", toString(someRandomField));

function isBigger(animalOne, animalTwo) {
  switch (animalOne) {
    case /* Bear */0 :
        return animalTwo !== 0;
    case /* Rabbit */1 :
        return false;
    case /* Deer */2 :
        switch (animalTwo) {
          case /* Rabbit */1 :
              return true;
          case /* Bear */0 :
          case /* Deer */2 :
              return false;
          
        }
    
  }
}

var nextTurn = /* Cross */0;

exports.nextTurn = nextTurn;
exports.toString = toString;
exports.someRandomField = someRandomField;
exports.isBigger = isBigger;
/*  Not a pure module */
