// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var accountOne = {
  TAG: /* Facebook */1,
  _0: "Josh",
  _1: 26
};

var accountTwo = {
  TAG: /* Instagram */0,
  _0: "Jenny"
};

console.log(accountOne, accountTwo);

function handleAnswer(input) {
  if (input === /* Yes */0) {
    return "foo";
  } else if (input === /* No */1) {
    return "bar";
  } else {
    return "other";
  }
}

console.log("First Answer:", handleAnswer(/* Maybe */2));

function handleAnswerSwitch(a) {
  switch (a) {
    case /* Yes */0 :
        return " ..It was a Yes type";
    case /* No */1 :
        return " ..It was a No type";
    case /* Maybe */2 :
        return "other";
    
  }
}

console.log("Final Answer:", " ..It was a Yes type");

console.log("Final Answer:", " ..It was a No type");

console.log("Final Answer:", "other");

var pet1 = /* Dog */0;

var pet2 = /* Dog */0;

exports.pet1 = pet1;
exports.pet2 = pet2;
exports.accountOne = accountOne;
exports.accountTwo = accountTwo;
exports.handleAnswer = handleAnswer;
exports.handleAnswerSwitch = handleAnswerSwitch;
/*  Not a pure module */
